/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PricesIndexRouteImport } from './routes/prices.index'
import { Route as PricesSlugRouteImport } from './routes/prices.$slug'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesIndexRoute = PricesIndexRouteImport.update({
  id: '/prices/',
  path: '/prices/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesSlugRoute = PricesSlugRouteImport.update({
  id: '/prices/$slug',
  path: '/prices/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/events': typeof EventsRoute
  '/merch': typeof MerchRoute
  '/news': typeof NewsRoute
  '/stories': typeof StoriesRoute
  '/prices/$slug': typeof PricesSlugRoute
  '/prices/': typeof PricesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/events': typeof EventsRoute
  '/merch': typeof MerchRoute
  '/news': typeof NewsRoute
  '/stories': typeof StoriesRoute
  '/prices/$slug': typeof PricesSlugRoute
  '/prices': typeof PricesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/events': typeof EventsRoute
  '/merch': typeof MerchRoute
  '/news': typeof NewsRoute
  '/stories': typeof StoriesRoute
  '/prices/$slug': typeof PricesSlugRoute
  '/prices/': typeof PricesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/events'
    | '/merch'
    | '/news'
    | '/stories'
    | '/prices/$slug'
    | '/prices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/events'
    | '/merch'
    | '/news'
    | '/stories'
    | '/prices/$slug'
    | '/prices'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/events'
    | '/merch'
    | '/news'
    | '/stories'
    | '/prices/$slug'
    | '/prices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  EventsRoute: typeof EventsRoute
  MerchRoute: typeof MerchRoute
  NewsRoute: typeof NewsRoute
  StoriesRoute: typeof StoriesRoute
  PricesSlugRoute: typeof PricesSlugRoute
  PricesIndexRoute: typeof PricesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices/': {
      id: '/prices/'
      path: '/prices'
      fullPath: '/prices/'
      preLoaderRoute: typeof PricesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices/$slug': {
      id: '/prices/$slug'
      path: '/prices/$slug'
      fullPath: '/prices/$slug'
      preLoaderRoute: typeof PricesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  EventsRoute: EventsRoute,
  MerchRoute: MerchRoute,
  NewsRoute: NewsRoute,
  StoriesRoute: StoriesRoute,
  PricesSlugRoute: PricesSlugRoute,
  PricesIndexRoute: PricesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
